### ISSUE TITLE
Xcode 7 奔溃

### ISSUE THREAD

**Issue by johnlui** [ming1016/PagerTab#3]
模拟器和真机都奔溃，说没有设置 rootViewController：
Application windows are expected to have a root view controller at the end of application launch

**Comment by johnlui** [comment]
是我不会设置么== 我一直用 Swift，从 Main.Storyboard 启动，没从 main.m 启动过。

**Comment by litt1e-p** [comment]
yeah, it wil be crashed in Xcode7 or Xcode7.2 beta. I modified the AppDelegate.m with below codes and it works well:
- self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
- self.window.rootViewController = [[ViewController alloc] init];
- [self.window makeKeyAndVisible];
- //[SMTopWindow work];

**Comment by ming1016** [comment]
已修复，多谢@litt1e-p
